{% set name = "pydm" %}
{% set version = "1.27.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8ae90f31df22ae05f258566208dc43eeea135924583d663d55f62f9a291f3eb9

build:
  noarch: python
  number: 0
  entry_points:
    - pydm = pydm_launcher.main:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
    - pyqt =5
    - qtpy >=2.2.0
  run:
    - python >={{ python_min }}
    - six
    - numpy
    - scipy
    - pyepics
    - pyqt =5
    - pyqtgraph
    - qtpy >=2.2.0
    - entrypoints

test:
  requires:
    - python {{ python_min }}
  imports:
    - pydm

about:
  home: https://github.com/slaclab/pydm
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: OTHER
  license_file: LICENSE.md
  summary: Python Display Manager

  description: |
    PyDM is a PyQt-based framework for building user interfaces for control systems.
    The goal is to provide a no-code, drag-and-drop system to make simple screens,
    as well as a straightforward Python framework to build complex applications.
  doc_url: https://slaclab.github.io/pydm/
  dev_url: https://github.com/slaclab/pydm

extra:
  recipe-maintainers:
    - nstelter-slac
    - zllentz
    - yektay
    - jbellister-slac
