{% set name = "pydm" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/slaclab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 770cd76f3d5fe9bc27594e68d6f88d3b77e764892115accf7dbfe09e38c52509

build:
  noarch: python
  number: 2
  entry_points:
    - pydm = pydm_launcher.main:main

requirements:
  host:
    - python
    - pip
    - setuptools
    - pyqt >=5
    - qtpy
  run:
    - python
    - six
    - numpy
    - scipy
    - pyepics
    - requests
    - pyqt >=5
    - pyqtgraph
    - qtpy

test:
  imports:
    - pydm

about:
  home: https://github.com/slaclab/pydm 
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: OTHER
  license_file: LICENSE.md
  summary: 'Python Display Manager'

  description: |
    PyDM is a PyQt-based framework for building user interfaces for control systems.
    The goal is to provide a no-code, drag-and-drop system to make simple screens,
    as well as a straightforward Python framework to build complex applications.
  doc_url: https://slaclab.github.io/pydm/
  dev_url: https://github.com/slaclab/pydm

extra:
  recipe-maintainers:
    - hhslepicka
